// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuh5e6OsM92P7c11XKOKxhZxsLEc0Q8PE',
    appId: '1:72448395530:web:dadc8947a300cbea6c12f3',
    messagingSenderId: '72448395530',
    projectId: 'zingdb-9653d',
    authDomain: 'zingdb-9653d.firebaseapp.com',
    storageBucket: 'zingdb-9653d.firebasestorage.app',
    measurementId: 'G-5D61PS4HN6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpYIa5zdOsjhZ-shoKZmV2q9QBCqQKd4',
    appId: '1:72448395530:android:da22c96efebd2cd06c12f3',
    messagingSenderId: '72448395530',
    projectId: 'zingdb-9653d',
    storageBucket: 'zingdb-9653d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOJDS-D7T7yhoc7eZSr7brcVcMw3_lulQ',
    appId: '1:72448395530:ios:21be0bbf111eef106c12f3',
    messagingSenderId: '72448395530',
    projectId: 'zingdb-9653d',
    storageBucket: 'zingdb-9653d.firebasestorage.app',
    iosBundleId: 'com.zing.app.zing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOJDS-D7T7yhoc7eZSr7brcVcMw3_lulQ',
    appId: '1:72448395530:ios:21be0bbf111eef106c12f3',
    messagingSenderId: '72448395530',
    projectId: 'zingdb-9653d',
    storageBucket: 'zingdb-9653d.firebasestorage.app',
    iosBundleId: 'com.zing.app.zing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuh5e6OsM92P7c11XKOKxhZxsLEc0Q8PE',
    appId: '1:72448395530:web:e002b48698844d916c12f3',
    messagingSenderId: '72448395530',
    projectId: 'zingdb-9653d',
    authDomain: 'zingdb-9653d.firebaseapp.com',
    storageBucket: 'zingdb-9653d.firebasestorage.app',
    measurementId: 'G-RRVWFB3CQ6',
  );
}
